### ISSUE TITLE
text color is yellow instead of white on android

### ISSUE THREAD

**Issue by julesx** [alexrainman/SegmentedControl#10]
https://github.com/alexrainman/SegmentedControl/blob/master/SegmentedControl/SegmentedControl.FormsPlugin.Android/SegmentedControlImplementation.cs#L100

i believe this should be

v.SetTextColor(Color.FromHex("#00ffffff").ToAndroid());

> the developer can explicitly provide an 8-digit number that completely specifies the Alpha, Red, Green, and Blue channels, in that order.

**Comment by alexrainman** [comment]
I just made the Android version behaves exactly like ios where unselected tabs are transparent a selected one text is transparent also.

**Comment by alexrainman** [comment]
I understand your point now. Thanks

**Comment by julesx** [comment]
just to add, i think you should consider making the Tint color be the Accent color by default, it looks much better than the default color being used right now (which i believe is the default radio button colors)

**Comment by alexrainman** [comment]
I am using TintColor. I dont know what you mean by accent.

**Comment by julesx** [comment]
https://developer.xamarin.com/guides/xamarin-forms/working-with/colors/

Color.Accent
Color.Default

these are named colors that are defined by the android OS theme.

**Comment by alexrainman** [comment]
I still dont understand what you want :). I am using TintColor in unselected tabs text color, borders and selected tan background. Exactly as iOS component.

**Comment by julesx** [comment]
set the Tint color to default to Accent

**Comment by AndriiTsok** [comment]
@julesx I agree we need an additional property for unselected background color and maybe for text color (selected normal).

For instance: http://prntscr.com/diq6y7 

Looking for work around to make the unselected items background transparent and text color black.

**Comment by alexrainman** [comment]
I am using TintColor in unselected tabs text color, borders and selected tab background. Exactly as iOS component and that wont change. I am adding a property to set selected tab text color, normally to provide the hability to match container background color, as transparent doesnt works.

**Comment by alexrainman** [comment]
UISegmentedControl uses TintColor for selected segment background color, unselected segments text color and border color. I am matching that.

**Comment by julesx** [comment]
If you set the text colour to Color.Default it should be visible both selected and not. A property certainly wouldn't hurt though.

**Comment by alexrainman** [comment]
As i said, Android control is intent to mimic iOS counterpart and that's the way it should be.

**Comment by flippinloud** [comment]
If you set the background color (to white for instance), it colors outside the border of the control. It means if I want white buttons with blue selected button and blue borders, there is white drawn outside the button itself. 

                                        <segControl:SegmentedControl x:Name="YearSplitButton" 
                                            TintColor="Blue"
                                            BackgroundColor="White"
                                            SelectedTextColor="White"
                                            SelectedSegment="0" Grid.Row="0" Grid.ColumnSpan="3"  HeightRequest="30" Margin="0,10,0,10">
                                          <segControl:SegmentedControl.Children>
                                            <segControl:SegmentedControlOption Text="2016" />
                                            <segControl:SegmentedControlOption Text="2017" />
                                            <segControl:SegmentedControlOption Text="2018" />
                                          </segControl:SegmentedControl.Children>
                                        </segControl:SegmentedControl>
