### ISSUE TITLE
Issues binding command to event 

### ISSUE THREAD

**Issue by stephenhauck** [alexrainman/SegmentedControl#13]
I have the following code in my application ...

xmlns:b="clr-namespace:Corcav.Behaviors;assembly=Corcav.Behaviors"

later in XAML...

 <controls:SegmentedControl x:Name="segmentControlFeeding" Grid.Row="6" Grid.Column="1" Grid.ColumnSpan="2" HeightRequest="50" WidthRequest="200"  HorizontalOptions="StartAndExpand" IsEnabled="true"  >
              <controls:SegmentedControl.Children>
                <controls:SegmentedControlOption Text="Yes" />
                <controls:SegmentedControlOption Text="No" />
              </controls:SegmentedControl.Children>
              <b:Interaction.Behaviors>
                <b:BehaviorCollection>
                  <b:EventToCommand EventName="ValueChanged" Command="{Binding SegmentControlFeedingValueChangedCommand}" />
                </b:BehaviorCollection>
              </b:Interaction.Behaviors>
            </controls:SegmentedControl>

This code work on other segment controls but not yours for some reason.... just thought I would let you know...

**Comment by alexrainman** [comment]
Will take a look.

**Comment by alexrainman** [comment]
What is Corcav.Behaviors? A namespace with your behaviors or a third party library?

**Comment by stephenhauck** [comment]
Yes, check it out (https://github.com/corradocavalli/Corcav.Behaviors) ...
it lets you map events to command and such easily...lots of people use it

Stephen

**Comment by julesx** [comment]
just as a note here, you can bind against the selected segment and just monitor for changes, you don't really need event to command.

**Comment by stephenhauck** [comment]
You need the event to command when you are using MVVM .....
How else to I get the selected item changed notification event back in the
view model to apply appropriate actions / logic that might depend on the
value selected?

Stephen

**Comment by julesx** [comment]
Using MVVM, you have a property like `SelectedSegmentedControlIndex`

`<abstractions:SegmentedControl SelectedSegment="{Binding SelectedSegmentedButtonIndex">`

when the `Set` fires against `SelectedSegmentedButtonIndex`, take your action.

**Comment by stephenhauck** [comment]
I will check again.. thanks for follow up with me....
Right now I am in the middle of figuring out why my project is no longer
functional after the latest Xamarin update.....

**Comment by alexrainman** [comment]
@julesx that should be the approach. Thanks
