### ISSUE TITLE
IsEnabled has no effect on Android

### ISSUE THREAD

**Issue by julesx** [alexrainman/SegmentedControl#14]
`<abstractions:SegmentedControl IsEnabled="False" />`

setting the IsEnabled property to false doesn't seem to do anything on Android.  It should disable all the buttons in the control.  On iOS it works fine.

**Comment by alexrainman** [comment]
Let me work on that one.

**Comment by alexrainman** [comment]
Its fixed. Will release later today.

**Comment by julesx** [comment]
Setting IsEnabled back to true after having set it to false does not re-enable the control.

**Comment by alexrainman** [comment]
Yes i missed that one. Next.
