### ISSUE TITLE
Transparent Background for default segments. #question

### ISSUE THREAD

**Issue by AndriiTsok** [alexrainman/SegmentedControl#15]
I stuck with a silly issue. Trying to make the segmented control for android to look consistent with the iOS. On iOS the background is transparent for unselected segments, for android is just white.
Android: http://prntscr.com/dl29wr

Any suggestions how to make the same transparent background?
Thanks.

**Comment by alexrainman** [comment]
Which version of the control are you using? That have been already implemented. Alsoa property has been added to make the selected segment text color match the background.

**Comment by AndriiTsok** [comment]
I'm using 1.2.2. 
Yeah, I know about the Selected text and that's a good stuff!

Just struggling with this white background. Event if I set the background for segment or segmented control to Red, Green, Transparent - it still renders white.

**Comment by alexrainman** [comment]
Upgrade to latest one. You will get transparent background and the new property.
