### ISSUE TITLE
strange colors with disabled android control

### ISSUE THREAD

**Issue by julesx** [alexrainman/SegmentedControl#16]
i have 4 items in my segmented button control, using a custom TintColor.

when the control is loaded, i toggle it to disabled.

the TintColor of the first and last button are incorrectly using the default TintColor (blue in my case), while the middle two buttons are correctly greyed out to indicate their disabled status.

future button presses (which disable the control) have all buttons as correctly greyed out, with no tint color showing through when disabled.

**Comment by alexrainman** [comment]
Let me do some test.

**Comment by alexrainman** [comment]
When you exactly turn the control disabled?

**Comment by julesx** [comment]
the page loads with the control enabled

i kick off a background fetch operation which disables the control

when the fetch completes i toggle IsEnabled

i am doing everything via bindings

**Comment by alexrainman** [comment]
Did you solve this?

**Comment by julesx** [comment]
The issue is still occurring. Not sure what I am to solve. it appears that the control's tint colour is being incorrectly overridden when it is disabled.

**Comment by alexrainman** [comment]
Ok

**Comment by oriolnoya** [comment]
I solved it adding my custom colors on the colors.xml of my project using the same names that it uses for styling. For example:

`<color name="normal">#ffffff</color>`
`<color name="selected">#f6981a</color>`
