### ISSUE TITLE
How can I implement this using code (not xaml)?

### ISSUE THREAD

**Issue by triplumix** [alexrainman/SegmentedControl#17]
How do I add the segment using code? 
I tried the code below, but I get SegmentedControl doesn not contain a definition for Children ( http://i.imgur.com/69TQpMi.png )

I tried with ItemsSource, but won't work either.

```
                        var segmentOption = new SegmentedControlOption();
			var segmentOption2 = new SegmentedControlOption();
			segmentOption.Text = "option 1";
			segmentOption2.Text = "option 2";

			var segment = new SegmentedControl
			{
				Children = {
				  	segmentOption,
				 	segmentOption2
				}
			};
```

Thanks!

**Comment by alexrainman** [comment]
Of course SegmentedControl has Children property

```
var segControl = new SegmentedControl() { 
	Children = new List<SegmentedControlOption>() { 
		new SegmentedControlOption() { Text = "ONE" },
		new SegmentedControlOption() { Text = "TWO" }
	} 
};
```

**Comment by triplumix** [comment]
@alexrainman 
Forgot to mention, tried that before.

http://i.imgur.com/Ag63lnt.png

Now it says type name FormsPlugin doesn't exists

**Comment by triplumix** [comment]
I guess I'm missing something...

**Comment by alexrainman** [comment]
I dont know what but yes :)

**Comment by alexrainman** [comment]
Remove this froms your using area: SegmentedControl.FormsPlugin.Abstractions

**Comment by triplumix** [comment]
Now I have the first error, with "Children"

**Comment by alexrainman** [comment]
I have no idea :)

**Comment by triplumix** [comment]
Ok, np, thanks

**Comment by alexrainman** [comment]
Do you have another class with the same name?

**Comment by triplumix** [comment]
Yup. That was the problem. Thanks for pointing it out ;-)
Keep up the good work

**Comment by triplumix** [comment]
I feel like punching myself :))

**Comment by alexrainman** [comment]
👍
