### ISSUE TITLE
Blue color on first and third control

### ISSUE THREAD

**Issue by cipu** [alexrainman/SegmentedControl#19]
Hi,
I have three segmented control and I set 
```
TintColor = Color.White,
SelectedTextColor = Color.FromHex("#0f2e48"),
```

I have, instead, blue color when I select the first and the third one, otherwise it is correct.  The second one, in the middle, is ok.

What will I do to have all with the same color? 

I'm using the last version of plugin: 1.2.4

**Comment by julesx** [comment]
i think you are seeing the same issues as me, but it only seems to occur when control is disabled.

is this happening on all platforms?  for me it is only an issue on android.

**Comment by cipu** [comment]
Only on Android, on iOS works fine...but my controls are not disabled...rather, all controls have _IsEnabled = true_

**Comment by julesx** [comment]
just want to bump this.  the colors on android are really strange.  they work on some pages, but not on others, or they only half work, not sure what is going on.

**Comment by Festyk** [comment]
I wan to bump it too. I am not playing with enabled/disable states but I also see blue borders and background selection color on first and last element.

**Comment by cipu** [comment]
I've solved with this solution

https://github.com/alexrainman/SegmentedControl/issues/16#issuecomment-274048223
