### ISSUE TITLE
Binding against SelectedText

### ISSUE THREAD

**Issue by julesx** [alexrainman/SegmentedControl#22]
`    <abstractions:SegmentedControl SelectedText="{Binding SwitchValue}">`

No property, bindable property, or event found for 'SelectedText'

**Comment by alexrainman** [comment]
What do you want to do with this?

**Comment by julesx** [comment]
I assumed we could use this instead of binding against the index to just get the text of whatever cell is selected.

**Comment by alexrainman** [comment]
Nope. Thats not the functionality of that property. I was planing to remove it.

**Comment by julesx** [comment]
Your call. I could see it being useful. If it shouldn't work though, you should remove it!

**Comment by carl-neng** [comment]
Hello sir. Can you show us about SegmentedControl binding items and selected text change? Because I try to use it with mvvm pattern. So please help me.

**Comment by alexrainman** [comment]
This property has been removed. Instead you will be able to bind to SelectedSegment from MVVM.
