### ISSUE TITLE
SegmentedControlOption are getting duplicated on android rotation (ViewCell inside a ListView)

### ISSUE THREAD

**Issue by julesx** [alexrainman/SegmentedControl#23]
If you put a SegmentedControl into a `ViewCell` which is part of a `ListView`, and then rotate the device, the `SegmentedControlOption`s are once again added to the control, causing a duplication.  Rotating the device again repeats the behavior indefinitely.

It seems like the OnElementChanged method is getting re-triggered incorrectly.  There is no issue on iOS, only Android.

**Comment by julesx** [comment]
@alexrainman i hope we didn't scare you away.  this is a great control.

**Comment by alexrainman** [comment]
@julesx not at all. I have been busy with work. I hope to have some time this week to work on this.

**Comment by julesx** [comment]
I'll add that it doesn't seem to be rotation specifically, but more the list view rows getting their size re-calculated.  if i manipulate my listview by adding or removing other rows, the same duplication issue occurs

**Comment by alexrainman** [comment]
Hi there. I am back in business. I fixed all the issues less this one. Will try to reproduce.

**Comment by alexrainman** [comment]
I was able to fix it but the very first time text is aligned to left. Trying to solve that.

**Comment by alexrainman** [comment]
Solved.
