### ISSUE TITLE
Windows Mobile?

### ISSUE THREAD

**Issue by TonyLugg** [alexrainman/SegmentedControl#25]
I take it Windows Mobile is not supported?  Can you add support please?

**Comment by alexrainman** [comment]
I have been working on it for a while :)

**Comment by TonyLugg** [comment]
Awesome.  That’s the only thing stopping me from using it. ☺

Tony Lugg
C-TAP Corp.
Tel: 780-481-9017
Cel: 780-991-3526
www.vdis.com<http://www.vdis.com/>

Microsoft Certified Partner

**Comment by alexrainman** [comment]
Ok. Also, take a look at my CarouselView for Xamarin.Forms

**Comment by TonyLugg** [comment]
I saw that.  It would be better than the built in CarouselPage.

**Comment by alexrainman** [comment]
It uses platform specific controls: Android ViewPager and iOS UIPageViewController

**Comment by TonyLugg** [comment]
And on Windows?

**Comment by alexrainman** [comment]
FlipView

**Comment by TonyLugg** [comment]
Cool, good work!
