### ISSUE TITLE
Change font

### ISSUE THREAD

**Issue by gusmanb** [alexrainman/SegmentedControl#28]
Is it possible to change font family/font size?

**Comment by KarthikeyanSekar93** [comment]
Create the Custom render  of your SegmentControl Add the two Line. its working for me. If you need on Xaml Just create the custom Control on PCL then refer the values then use these two lines  on **OnElementChanged** Method
```
var myFont = UIFont.FromName("FontName", 20f);
nativeControl.SetTitleTextAttributes(new UITextAttributes() { Font = myFont }, UIControlState.Normal);

```

**Comment by LeoJHarris** [comment]
@KarthickeyanSekar @alexrainman Why couldnt this simple integration be implemented in the library, seems like a straight forward implementation? Then simply have a FontTextSize on the SegmentedControlOption..
