### ISSUE TITLE
Could not load type 'SegmentedControl.FormsPlugin.Android.SegmentedControlRenderer'

### ISSUE THREAD

**Issue by shineon84** [alexrainman/SegmentedControl#3]
Hi!
Your library is very helpful, it does exactly what i want. Good job!
But unfortunately, with the latest release of Xamarin.Forms there is a problem.

The new release of Xamarin.Forms (2.3.3.152-pre2) has entroduced an error in many libraries which use custom renderers, and your library is affected too.

Here is the error I get:
`Could not load type 'SegmentedControl.FormsPlugin.Android.SegmentedControlRenderer' from assembly 'SegmentedControl.FormsPlugin.Android, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null'.`

Here are some links about the same problem with other libraries:
https://github.com/luberda-molinet/FFImageLoading/issues/313
https://github.com/PrismLibrary/Prism/issues/770

It seems that the solution is the following:
> The latest (2.3.3.152-pre2) XF exposes an abstract CreateNativeControl that needs to be implemented on the renderers and all previous UI libraries stopped working for me.
<

Could you fix the problem of the library, please? Thank you very much!!!

**Comment by alexrainman** [comment]
Latest Xamarin released has introduced a lot of problems. I will take a look. Thanks.

**Comment by alexrainman** [comment]
Anyway, you are talking about a pre-release version. I wont push an update not until it becomes an official release. Thanks.

**Comment by shineon84** [comment]
Hi alex, 
You are right, is a pre-release version and maybe it will be fixed in production release. At the moment I've downgraded xamarin.forms to 2.3.2.127 and your library works perfectly.
Thank you!

**Comment by kevongreen** [comment]
Hey, thanks for this plugin, however, we're still getting this error running Xamarin 3.1.0.697729
