### ISSUE TITLE
Segment Text Misaligns when page is left, returned to

### ISSUE THREAD

**Issue by wozniakbe** [alexrainman/SegmentedControl#30]
I am using the segmented control on one page tab, but when I navigate to another tab, make an API call, and return, the text is misaligned to the left. I am not editing the text alignment at all, any explanation for this?

**Comment by alexrainman** [comment]
Platform?

**Comment by wozniakbe** [comment]
Only occurs on Android

**Comment by InquisitorJax** [comment]
Happens as soon as I tap the control option. TintColor also not being applied. Android API 19. nuget 1.2.4

**Comment by alezhuk** [comment]
The same was for me. I've fixed that on Android by explicitly setting height of segment control.

**Comment by wozniakbe** [comment]
How did you explicitly set the height in order for it to work?

Also @InquisitorJax in order to work around the tint color not being applied, you can explicitly set the color after it has been rendered (i.e. put in some method and call it after the view is initialized).

**Comment by alezhuk** [comment]
My segment was inside a grid, so it was defined in row as **RowDefinition Height="Auto"**, so I've
set **RowDefinition Height="60"** and for me it was fixed on Android

**Comment by wozniakbe** [comment]
@alezhuk thank you, I had the same row definition set to Auto and changing it to a numeric value fixes the issue.
