### ISSUE TITLE
UWP Support ?

### ISSUE THREAD

**Issue by dbolak** [alexrainman/SegmentedControl#31]
Would be wonderful to have Universal Windows support !

**Comment by kavitPatel** [comment]
I am also looking for UWP support, please let me know if it is available.

**Comment by 1iveowl** [comment]
Inspired by this library I created a .NET Standard based Segmented Control library that also supports UWP [Plugin Segmented Control for .NET Standard](https://github.com/1iveowl/Plugin.SegmentedControl)

@alexrainman I first tried to create a PR for this library, but I was unable to make the git clone work. Not sure why, but I VS 2017 was unable to open the solution in any workable state. Hence I chose to be inspired instead. Feel free to back port whateven I've done to make UWP work to this library if you want.

**Comment by alexrainman** [comment]
Going to include your UWP implementation in my plugin.
