### ISSUE TITLE
ValueChanged event no longer bindable from XAML

### ISSUE THREAD

**Issue by djcparker** [alexrainman/SegmentedControl#37]
Current version: 1.3.1 
In previous versions I was able to use the EventToCommandBehavior to bind the ValueChanged event.
This now causes an exception as the event seems to have been removed.  Looking at the code it looks like it has been replaced with a public property of type EventHandler.

Intellisense does not pick up the ValueChanged event either.

Previous code: 

 ```
       <segment:SegmentedControl 
                Grid.Row="0"
                Margin="20,10"
                x:Name="SelectSegment" 
                TintColor="{StaticResource accent}" 
                SelectedSegment="{Binding SelectedPosition, Mode=TwoWay}" >
            <segment:SegmentedControl.Behaviors>
                <behavior:EventToCommandBehavior EventName="ValueChanged" Command="{Binding SegmentChangedComand}"/>
            </segment:SegmentedControl.Behaviors>

            <segment:SegmentedControl.Children>
                <segment:SegmentedControlOption Text="Default" />
                <segment:SegmentedControlOption Text="Saved" />
            </segment:SegmentedControl.Children>
        </segment:SegmentedControl>

```

This behavior cannot attach to ValueChanged as it no longer appears as an event.

`  <behavior:EventToCommandBehavior EventName="ValueChanged" Command="{Binding SegmentChangedComand}"/>
`

Please let me know if you need more information.

**Comment by alexrainman** [comment]
Do it from code. I had to change it so i can call it from the renderers.

**Comment by valdetero** [comment]
@djcparker I'm not sure how your `EventToCommandBehavior` is implemented, but I changed mine to add this and it works for this specific scenario.

```c#
EventInfo eventInfo = AssociatedObject.GetType().GetRuntimeEvent(name);
if (eventInfo == null)
{
    //HACK: for Eventhandler field that isn't an event
    var fieldInfo = AssociatedObject.GetType().GetRuntimeField(name);
    if (fieldInfo?.FieldType == typeof(EventHandler))
    {
        MethodInfo mi = typeof(EventToCommandBehavior).GetTypeInfo().GetDeclaredMethod(nameof(OnEvent));
        eventHandler = mi.CreateDelegate(typeof(EventHandler), this);
        fieldInfo.SetValue(AssociatedObject, eventHandler);
        return;
    }

    throw new ArgumentException($"{nameof(EventToCommandBehavior)}: Can't register the '{EventName}' event.");
}
```

Not sure if it's the best method but it gets the job done.

**Comment by djcparker** [comment]
@valdetero - thanks!  I worked around it a different way. but I like the hack :)
