### ISSUE TITLE
SelectedSegment MVVM doesn't update

### ISSUE THREAD

**Issue by maciz84** [alexrainman/SegmentedControl#38]
The SelectedSegment property does not update the ViewModel. I have Inotifypropertychanged in my ViewModel and nothing happens?

Any help on this?

**Comment by alexrainman** [comment]
The property binding mode is not two ways. I am exploring a way to make it two ways.

**Comment by maciz84** [comment]
Hi Alex,
Correct it would be nice though :)
Good job on the control though

**Comment by maciz84** [comment]
So should I use OneWayToSource binding instead?

**Comment by maciz84** [comment]
I get this error message:

System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation.

When I navigate back to the page with the SegmentedControl. Well makes it unusable in my scenario which is a shame?

**Comment by djcparker** [comment]
Really? I am using version 1.3.1 with Binding and it works well. In fact I have a segment and a carousel that share the position:

```
       <segment:SegmentedControl 
                Grid.Row="0"
                Margin="20,10"
                x:Name="SelectSegment" 
                TintColor="{StaticResource accent}" 
                SelectedSegment="{Binding SelectedPosition, Mode=TwoWay}" >
            <segment:SegmentedControl.Children>
                <segment:SegmentedControlOption Text="Default" />
                <segment:SegmentedControlOption Text="Saved" />
            </segment:SegmentedControl.Children>
        </segment:SegmentedControl>

        <carousel:CarouselViewControl 
            Grid.Row="1"
            x:Name="SelectCarousel"
            VerticalOptions="FillAndExpand" 
            HorizontalOptions="FillAndExpand"
            AnimateTransition="True"
            Position="{Binding SelectedPosition, Mode=TwoWay }">
            <!-- templates are added in code behind -->
        </carousel:CarouselViewControl>

```
Unless I have not understood the issue?

**Comment by alexrainman** [comment]
I cannot know why you get that exception if you don't provide a demo project.

**Comment by maciz84** [comment]
Hi Guys,

I am sorry for the false alarm. It does work fine but it appears my code was conflicting somewhere with MVVMLight library.

I apologise for this the control is just fine:)

**Comment by alexrainman** [comment]
👍

**Comment by maciz84** [comment]
Again great work :+1:
