### ISSUE TITLE
Swipe feature

### ISSUE THREAD

**Issue by KarthikeyanSekar93** [alexrainman/SegmentedControl#39]
how to  swipe Using Change the Tab?

**Comment by alexrainman** [comment]
Can you explain yourself?

**Comment by KarthikeyanSekar93** [comment]
How to change the tab using swipe feature in segment control?.

**Comment by alexrainman** [comment]
I still dont get what you want? Swipe? Swipe what? If you want to change the selected tab as you swipe something like a Carousel, use/change SelectedSegment property.
