### ISSUE TITLE
Doesn't display on android inside scrollview

### ISSUE THREAD

**Issue by CarlosMobileAppDeveloper** [alexrainman/SegmentedControl#40]
It seems that if the main container is not a StackLayout then the segmentedControl does not appear. This is occurring when the segmentedControl sits inside a scrollView

E.g. 
<ContentPage>
   <ScrollView>
        <StackLayout x:Name="segContainer">
 etc

**Comment by alexrainman** [comment]
Is this solved?

**Comment by JosHuybrighs** [comment]
Is this maybe because of the delayed instantiation in size_changed (instead of element_changed)? See issue 45.

**Comment by alexrainman** [comment]
ScrollView is not a container itself so there's no layout request. You need something to wrap the control: StackLayout, Grid, AbsoluteLayout or RelativeLayout. Then you wrap in ScrollView when you need long content to be scrollable.

**Comment by alexrainman** [comment]
```
    <ScrollView>
        <StackLayout x:Name="segContainer"
                     Padding="12"
                     Spacing="12">
            <controls:SegmentedControl x:Name="SegControl">
                <controls:SegmentedControl.Children>
                    <controls:SegmentedControlOption Text="Items" />
                    <controls:SegmentedControlOption Text="Notes" />
                    <controls:SegmentedControlOption Text="Approvers" />
                    <controls:SegmentedControlOption Text="Attachments" />
                </controls:SegmentedControl.Children>
            </controls:SegmentedControl>
            <StackLayout x:Name="SegContent" />
        </StackLayout>
    </ScrollView>
````
