### ISSUE TITLE
Segment Text not centered on Android

### ISSUE THREAD

**Issue by zanesc** [alexrainman/SegmentedControl#41]
I have a segmented control with 2 tabs ("TODAY" and "ALL"). The control starts off with "TODAY" selected.

This works fine on iOS but on Android the text starts off initially centred, then when i change to "ALL" then back to "TODAY" the text becomes left aligned and stays that way.

Testing on a Nexus 7 (2013) on Android 7.1.2.

**Comment by zanesc** [comment]
Turns out this was due to having the Segment control within a grid, within a grid. I moved it out of the nested grid and it works now.

**Comment by beylkhanovdamir** [comment]
@zanesc 
same issue for me, but I think, that it's not universal solution of this problem

**Comment by LeoJHarris** [comment]
Facing the same issue, hardly an ideal solution what if the segment control needed to be in the grid (as in my case), this solution will not work for everyone..
