### ISSUE TITLE
Segmented Control Not rendering in Android

### ISSUE THREAD

**Issue by CRBUNN** [alexrainman/SegmentedControl#46]
Alex - thx for this control - it will be a huge help to me - I am using V1.3.1 (latest)

It works fine in Xamarin forms - for IOS
It does not render in Xamarin forms for android - i do have the RenderInit code in MainActivity.cs 

my phone# is 301-785-3345
or my email address is cbunn@chaneyenterprises.com

I am using Android target 7.0 - Nougat

thx v much
Chris

**Comment by johncruz24** [comment]
I have the same problem.

**Comment by CRBUNN** [comment]
Interesting
Thx

Sent from my iPhone

On Aug 1, 2017, at 11:03 PM, John Cruz <notifications@github.com<mailto:notifications@github.com>> wrote:


I have the same problem.

**Comment by johncruz24** [comment]
where you able to get it working @CRBUNN

**Comment by CRBUNN** [comment]
No call me
301785 3345

Sent from my iPhone

On Aug 2, 2017, at 2:56 PM, John Cruz <notifications@github.com<mailto:notifications@github.com>> wrote:


where you able to get it working @CRBUNN<https://github.com/crbunn>

**Comment by johncruz24** [comment]
@alexrainman do you know if this is working for android now?

**Comment by johncruz24** [comment]
I figured out the problem. You need to add HeightRequest @CRBUNN

**Comment by CRBUNN** [comment]
Thx v much

Sent from my iPhone

On Aug 3, 2017, at 3:54 PM, John Cruz <notifications@github.com<mailto:notifications@github.com>> wrote:


I figured out the problem. You need to add HeightRequest @CRBUNN<https://github.com/crbunn>

**Comment by phoenix214** [comment]
Thank you!

**Comment by pineapple216** [comment]
I've added a minimumheight request of 30 and the control still doesn't display for me on a Nexus 5 simulator, running Android 6

**Comment by pineapple216** [comment]
Does anyone have another work around, that does work?

**Comment by mikegottlieb** [comment]
I'm also seeing this after updating to XF 2.3.4 and updating the SegmentedControl to latest.

**Comment by alexrainman** [comment]
Next release will be compatible.
