### ISSUE TITLE
Doesn't work with Xamarin.Forms Previewer

### ISSUE THREAD

**Issue by tomKrueger** [alexrainman/SegmentedControl#49]
When trying to display page with SegmentedControl in Xamarin.Forms Previewer a Null Reference Exception is thrown.

In digging into the code it looks like nativeControl is null within SegmentedControlRenderer.Element_SizeChanged method.

Here is the line of code where nativeControl is set to null.
nativeControl = (RadioGroup)layoutInflater.Inflate(Resource.Layout.RadioGroup, null);

**Comment by alexrainman** [comment]
It works on previewer without any extra fix:

<img width="1286" alt="screen shot 2017-09-01 at 12 52 26 pm" src="https://user-images.githubusercontent.com/3793554/29981736-802f25ee-8f14-11e7-94c7-aa1ab6d9f477.png">
