### ISSUE TITLE
How to change selected segment color?

### ISSUE THREAD

**Issue by moogiis** [alexrainman/SegmentedControl#5]
> private void add_click(object sender, EventArgs e)
>   {
>           SegControl.SelectedSegment = 1;
>   }

**POSSIBLE??**

**Comment by alexrainman** [comment]
You use TintColor to change the selected segment color. I am releasing a new version that will have callbacks to change the selected segment programmatically.

**Comment by moogiis** [comment]
Thank you.

**Comment by alexrainman** [comment]
What exactly do you want here? Change selected tab programmatically or change tintcolor programmatically?

**Comment by alexrainman** [comment]
Next release.
