### ISSUE TITLE
Segmented Control Not Displaying on Second Page

### ISSUE THREAD

**Issue by tomKrueger** [alexrainman/SegmentedControl#51]
The Segmented Control displays on the first page navigated to, however, if you then navigate to another page, the SegmentedControl does not display.

I reproduced in the demo by doing the following.

1. Copied DemoPage and renamed to Demo2 (Class, Constructor, and in XAML).
2. Added button to DemoPage and on click navigated to Demo2.

```
private async void Button_Clicked(object sender, EventArgs e)
{
    await Navigation.PushAsync(new DemoPage2());
}
```

I am working on Android when testing out.  I would be happy to troubleshoot I anyone has ideas as to what to check.  My hunch is the LayoutInflater is not inflating into the DemoPage2 but I'm new to Android and coming up to speed.

Thanks for help!

**Comment by alexrainman** [comment]
Fixed. Next release.

**Comment by nbsoftware** [comment]
Hello.
This is again broken in new 2.0.0 - I've just checked.
Control isn't showing on pages that are navigated to via Navigation.PushAsync
See @tomKrueger example that shows the issue.
It was working in 1.3.4
