### ISSUE TITLE
Text becoming left aligned after tap

### ISSUE THREAD

**Issue by pfiggins** [alexrainman/SegmentedControl#60]
I have a strange issue where once tapped, my segmented control text becomes left aligned.

Before -
![seg_orig](https://user-images.githubusercontent.com/6193026/30568108-7998e3ba-9ca1-11e7-9aa4-f6d96d131d7c.PNG)

After -
![seg_left](https://user-images.githubusercontent.com/6193026/30568114-81069462-9ca1-11e7-9bcb-9946fd26f73d.PNG)

Any ideas?

**Comment by pfiggins** [comment]
Just wanted to circle back and let you know that it's being caused by handling the ValueChanged event. If I take that handler off the event, everything is fine. So it must be some sort of timing issue. Either way, for now what I have found to work is to make the control invisible and then visible. This causes a redraw and the text is again centered as expected.

**Comment by alexrainman** [comment]
Will take a look.

**Comment by alexrainman** [comment]
I cannot reproduce this. Can you tell me device and OS?

**Comment by zanesc** [comment]
This issues has been reported before. I even found a workaround once, but now even that does not work. Back to text being left aligned only happens on Android.

https://github.com/alexrainman/SegmentedControl/issues/59
https://github.com/alexrainman/SegmentedControl/issues/41
https://github.com/alexrainman/SegmentedControl/issues/30

**Comment by alexrainman** [comment]
This is more a Xamarin.Forms issue than the control itself. Thats why setting the HeightRequest fix it.

**Comment by pfiggins** [comment]
So what is the best workaround then? Can you implement something in the control to ensure it redraws properly? I'm still seeing this on any redraw and it's pretty annoying to have to hook into any event that may cause a redraw and make sure I hide/show this control. No other controls have this issue, so either they work around it or it's something specific to how this control operates.

**Comment by pfiggins** [comment]
Oh, and sorry I missed your earlier request. I'm personally seeing this on Android with genymotion generic tablets running api 23 and 25. I haven't really paid attention to which physical tablets do/don't have the issue.
