### ISSUE TITLE
Selected Text Color no Erases background

### ISSUE THREAD

**Issue by Finneyv** [alexrainman/SegmentedControl#63]
A previous version of this control allowed the background color of the page to show through where the text occurs, which allows me to not have to specify the Selected Text Color.  Just wondering how I can get this effect back.  Here is an example of the way it used to work.
![image uploaded from ios](https://user-images.githubusercontent.com/10379112/30826412-8d2cb934-a204-11e7-9547-e644fcfeb190.jpg)

**Comment by alexrainman** [comment]
Androd or iOS?

**Comment by alexrainman** [comment]
The issue and the description of the issue are the opposite thing.
