### ISSUE TITLE
Control is not working on Lollipop

### ISSUE THREAD

**Issue by darrenzully** [alexrainman/SegmentedControl#65]
I´m using this control in my apps and it works on all versions but Lollipop, do you have a fix or workaround for it?

**Comment by alexrainman** [comment]
Actually not. Sorry. Some APIs dont work in Lollipop.

**Comment by darrenzully** [comment]
Useless control.

**Comment by alexrainman** [comment]
Really? Then don't "use" it.

**Comment by alexrainman** [comment]
Wait a minute. The control should work on APIs >= 18. Can you provide StackTrace? Exception?

**Comment by darrenzully** [comment]
There are no exceptions, I'm using the control in the same way that your SecondPage example, when I click on one of the buttons the event is fired, but the control does not change the color and it's not selected.

**Comment by alexrainman** [comment]
Very strange. Will run some tests.

**Comment by darrenzully** [comment]
It seems to be that in Lollipop the page is not refreshing. In all the others apis it's working fine, but in Lol when you clicked on a button the page change other controls states but it's not reflected in the page.

**Comment by darrenzully** [comment]
I solved, your control is fine, and is very USEFULL :) 
On Lollipop there is a bug with PushAsync true, that crashes the app, I changed to false and it's working.
SORRY!
