### ISSUE TITLE
Segment triggers multiple times when loaded in a list

### ISSUE THREAD

**Issue by etiennestrydom** [alexrainman/SegmentedControl#67]
Hi! Thanks for the awesome plugin!

I'm facing a strange issue where the segment on-selected event is triggering multiple times when I load the segment in a ViewCell within a list. I tried to debug this issue, it looks like it is linked to initialising the page and the amount of segments I have.

For instance I push a page with a listview consisting of two items displaying 3 segments in each item. The 0 index on-selected event will then trigger 3 times on initialisation but thereafter triggers once on segment click. When I load the exact single item outside of the list the 0 index on-selected event triggers only once.

**Comment by alexrainman** [comment]
It will trigger one time for each segment you have.
