### ISSUE TITLE
White screen on iOS with new Xamarin.Forms update

### ISSUE THREAD

**Issue by asura1234** [alexrainman/SegmentedControl#68]
My app will appear as white screen if I have "SegmentedControlRenderer.Init(); in the AppDelegate.cs. Commenting this line out would result no visual for the segemented control but the other stuff would re-appear.

**Comment by etiennestrydom** [comment]
Xamarin.Forms: 2.5.0.91635
SegmentedControl.FormsPlugin: 1.3.4

My segments are all working on iOS. Are you loading the segments on your app's main page / startup page? Also make sure you are initiating the segments after:

`global::Xamarin.Forms.Forms.Init();`
