### ISSUE TITLE
SelectedSegment bindable property is OneWay by default

### ISSUE THREAD

**Issue by johankson** [alexrainman/SegmentedControl#7]
Shouldn't the SelectedSegment bindable property be TwoWay by default? In order to make it work you need to specify your binding like this.

`SelectedSegment="{Binding SelectedSegment, Mode=TwoWay}`

If it's by design, it should be added to the documentation.

**Comment by alexrainman** [comment]
Why you need it to be TwoWay? I am adding two methods to change selected tab and tint color programatically. Also, there's a event handler you can delegate to segmented control named ValueChanged, that method is called when SelectedSegment changes.

**Comment by alexrainman** [comment]
Actually SelectedSegment is TwoWay somehow because of this. When SelectedSegment changes, ValueChanged delegate gets called. Normally you subscribe to it to change the content.

**Comment by johankson** [comment]
The nuget version doesn't update a data bound property. It might be fixed in source. I needed it two way to update the property on the view model. (Classic mvvm style). Close the issue if you don't think it's a good idea. It's just how I use it.

**Comment by alexrainman** [comment]
You can make it TwoWay no matter if by default is OneWay and your ViewModel will be updated as any time a tab is selected, SelectedSegment property is updated and the setter will be called in the abstraction code, indeed you ViewModel :)

**Comment by johankson** [comment]
Just figured since it's an input control, two way would work out of the box without specifically setting it.(It does not unless you changed it since the 1.1 nuget package). Just my 2c. It's like making Entry one way. :) 

The event handler will not do any good since that would force you to be a bad person and put code in your code behind and he MVVM-gods would be displeased. :)

Unless I'm totally missing your point. Which is also a very possible reality.

**Comment by alexrainman** [comment]
Yes you are missing my point. ValueChanged event is to update the content container when selected segment changes and you can set SelectedSegment binding in TwoWay mode as Its setter will trigger when a tab is clicked :)

**Comment by erichedstrom** [comment]
Just to add my two cents, having TwoWay mode called out in the Readme would be helpful. I didn't know there was such an option and thought the binding to my ViewModel was broken until I found this issue. 

Regardless, thank you for sharing the SegmentControl! It's very helpful.

**Comment by alexrainman** [comment]
Sorry guys, the plugin seems to be abandoned  but its not. I just have been busy with my full time job. Will take care of the issues as soon as i can. Thanks
