### ISSUE TITLE
White cells look bad on dark android theme

### ISSUE THREAD

**Issue by julesx** [alexrainman/SegmentedControl#8]
Could we maybe get some options to change the colors?

On Android, if you don't specify any colors, it looks exactly like it does on iOS.  Could the unselected cells instead have the option of being transparent, and use the default text color?  Using a dark theme, it really doesn't look very good currently.

It seems like specifying the background color has no effect whatsoever on Android.
Changing the tint color still leaves you with the horrid-looking white cells.  Setting the TintColor to Default is closest to the desired behavior, except the unselected cells are white, which makes the text invisible.

**Comment by alexrainman** [comment]
Thats exactly the behavior of it: unselected cells will be white with text using tintColor. So, you want it to be transparent instead of white, dont?

**Comment by alexrainman** [comment]
Background color has not effect, tintColor instead. Basically you want same behavior as iOS where unselected cells are transparent. Makes sense.

**Comment by alexrainman** [comment]
Will do.

**Comment by julesx** [comment]
Yes, just you have to be careful about the text color.  I notice in your renderer you are hard coding it to white, i think you should be using some combination of Default or Accent, or let user specify.  Thanks for the great control.

**Comment by alexrainman** [comment]
Text color is equal to TintColor in unselected tabs and white in selected one. You want the selected one text color transparent?

**Comment by julesx** [comment]
Unselected cells should have a transparent background.
Selected cell background should be Accent. 
A text color of Default works for both these cases, I believe.
I am not sure the text color needs to change at all.

**Comment by alexrainman** [comment]
Fixed.
