### ISSUE TITLE
Causes strange behavior when used on a blackberry via android APK

### ISSUE THREAD

**Issue by julesx** [alexrainman/SegmentedControl#9]
When I load my android app on my blackberry, the page containing the segmented control refuses to display whatsoever.  Not sure what kind of information I can provide here.  You can't debug locally against a blackberry.  I am trying it on a Blackberry Z10, if that helps any.  I've never had any issues running my XF app on this blackberry before.  The same app is working great on my iPhone and Android.

**Comment by alexrainman** [comment]
The control requires Android 4.4 and up.

**Comment by julesx** [comment]
ahh this could very be well the problem.  is it possible for the package to warn or error if your project is targetting a lower version?  i am targetting 4.2

**Comment by alexrainman** [comment]
Yes, i can include something like that. The problem is InsetDrawable.getDrawable API is not supported in OS < 4.4, and it's needed in this plugin. Anyway, the market share for OS < 4.4 is really low.

:(

**Comment by julesx** [comment]
thanks.  not a big deal either way, would probably just be nice if the end user got a warning so they dont open up issues like this one :)
